### PR TITLE
Initial Streams Documentation Changes

### PR DESCRIPTION
**Pull request by Jshaffer7390**
# Description of change

Updated streams and channels documentation to better reflect the current state of the streams project prior to a MVP release.
The changes made were:
    - Refined the overview of streams to include the ed25519 signature scheme and x25519 key sharing
    - Protobuf3 is now known as Streams DDML
    - Removed the ChangeKey Function
    - Updated the tutorial to align with the new codebase and support multi-branching

# Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds new content)

# Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my changes

### CODE REVIEW

**Comment by Jshaffer7390** [comment]
> 
> 
> `The code` refers to the examples or channels implementation? Maybe `The example code`?
> 
> Relevant examples will be [here](https://github.com/iotaledger/streams/tree/master/examples) once binary branch is merged into master.

This has been addressed!

**Comment by JakeSCahill** [comment]
Hey guys, thanks for the PR ❤️ 

Just to document some outstanding things I found in my review:

- We need to remove references to the author's W-OTS and update how you create an author (this is in the creating-a-new-channel.md guide)
- We are missing a guide called multi-branch-sequence.md, which has been linked from the tutorial

**Comment by kwek20** [comment]
@JakeSCahill I have added the "multi-branch-sequence" tutorial, although its more of "why does this exist" page based on the specs. I will now address the other 2 points you mentioned, thanks for the review!

**Comment by kwek20** [comment]
There, all that is left is an image for the `Sequence` packet at `channels/1.2/images/sequencepacket.png`

**Comment by JakeSCahill** [comment]
Any more to come @kwek20 @Jshaffer7390 ? Not sure if the build issue is because it's a draft

**Comment by JakeSCahill** [comment]
This PR fixes the links and example in the Streams README: https://github.com/iotaledger/streams/pull/29

**Pull request merged**
