### PR TITLE
Add flink how to guide to readme and doc-index

### PR DESCRIPTION
**Pull request by Citrullin**
I guess that is the reason why the flink guide is not in the IRI menu, right?

### CODE REVIEW

**Comment by JakeSCahill** [comment]
Because this is a guide, can we change the title to an infinitve verb phrase. Something that will make someone want to read it like:
Generate Tangle statistics from ZMQ events

Also, can we add an embolded paragraph under the level 1 heading? Something that tells readers what the article is about, who it's for, and why they'd want to follow it.

**Comment by Citrullin** [comment]
@JakeSCahill Better? :)

**Comment by JakeSCahill** [comment]
Yeah 👍  just change the noun phrase to an imperative. So the 'Near real-time transaction stream processing' heading becomes 'Process transaction streams in near real time'

**Comment by Citrullin** [comment]
@JakeSCahill I think it is even more inviting now :) Thanks.

**Pull request merged**
