### PR TITLE
Add doc-index and an opening paragraph for SBC guide

### PR DESCRIPTION
**Pull request by JakeSCahill**

### CODE REVIEW

**Comment by jakubcech** [comment]
`Adds general/0.1/doc-index.md` - yes pls 😅

**Comment by Citrullin** [comment]
What do you think. Would it make sense to just split it into three guides: Set up SBC with Wifi only (No display port), Setup up SBC via display port and set up SBC with Ethernet only. It looks like if we combine everything it gets too confusing as I see now.

**Comment by JakeSCahill** [comment]
Great idea. I think that may be the best solution. Then readers can choose based on their SBC

**Comment by Citrullin** [comment]
The question is just: Where to place it? Keep it in general or do we want to have a new area?

**Comment by JakeSCahill** [comment]
Keep it in general and keep it in one article. Just use headings to separate the different tasks. Then at the beginning of the article direct readers to the heading that applies to them.

**Comment by Citrullin** [comment]
@JakeSCahill I am not sure if we should keep it in general. I am currently finishing the code for the Bluetooth Sensor Node Setup (6LoWPAN over Bluetooth) with the Go Client on the other side.
I will probably cover the following topics. I am not sure about the split yet:
- Client in Go (Compile protobuf files etc. Going through the code)
- 6LoWPAN over Bluetooth Setup on Host & Sensor device
- Simple general explanation of Bluetooth.
- POSIX socket server with protobuf messages (Going through the code)
- Some things about RIOT OS: Shell interaction, sensor driver etc. (Server is implemented in RIOT OS, but POSIX compatible, therefore OS independent.)

**Comment by JakeSCahill** [comment]
So the way I see it is that the **General** section is where we keep articles that are part of prerequisites for IOTA-based tasks.
---
**For example:**

We have the **IRI** section, which is where we keep IOTA-specific articles about the IRI such as 'run a node' or 'find neighbors'.

Under the **Prerequisites** heading of the 'run a node on Linux' article, we say that to complete the guide, you need a Linux operating system. We want to help users who aren't familiar with Linux, but we also don't want to clutter that article with information about what Linux is or how to use it.

So instead, we put general information about Linux VMs in the **General** section and link to it. This way, we can keep the IOTA article focussed on the task of running a node without explaining things like VMs to those who may already know about them or have one.
---
So for the SBC guides, I see those as 'prerequisite' material.

**For example:**

If you write an article about running a node on an SBC. You would say under the **Prerequisites** heading that to complete the guide, you need an SBC that's connected to the Internet. Then, you can link to the SBC setup guides in the **General** section.  That way, you keep the 'run a node on an SBC' article simple and focussed. Users who are familiar with SBC or who have one don't need to read about how to set one up, whereas those that don't have one can click the link and find out.

---

Regarding your question about where to split articles, **we should focus on tasks (how-to guides)**. Users want to know how to do something so that should be the focus. If the task requires users to know about a concept such as Bluetooth and the conceptual information is long, that information should go into its own article in **Concepts**. Likewise for reference material such as long tables or API references.

Just make sure to link to the articles in **Concepts** or **References**.

So, for the Bluetooth sensor node setup, what's the task? We should write a heading with an imperative verb that users can read and identify if they need it. Then, we can decide if it's an IOTA-based task or a prerequisite task that should go into the **General** section.

**Comment by Citrullin** [comment]
@JakeSCahill Okay, maybe some context helps. 
The overall topic:
- I want to run a sensor mesh network which sends data to the tangle Later: A network of IoT devices which also pay each other I need to:
	- Set up an SBC with cIRI, so that I have a local running full-node instance. In best case: I have a local network of full-nodes. Therfore I need:
		- To set up an SBC
		- Cross compile cIRI and run it on my SBC
	- Set up Bluetooth interface for my full-node, so that the UDP packets from the sensors can be routed to my app.
	- This middleware is creating transactions from these UDP packets.
		- Compiling protobuf files
		- What protobuf is?!
	- Set up the sensor node
		- Install ARM toolchain, J-Link software etc.
		- Explain a bit POSIX socket
		- Explain a bit Bluetooth (because it is low level stuff)
		- RIOT OS a bit, since it is used here.
	- Connecting the sensor nodes to my SBC and attach the data to the tangle.

I have a rough idea how to split it. What would make sense. But I am not sure where to put it. I am not sure if general is the right place, because it is only used for this whole IoT space. But theoretical, you can also connect your SBC to your home router, without the sensors.

**Comment by JakeSCahill** [comment]
Wow that sounds great, thanks for that 👍 

I can see a possible structure forming, so I'll explain my reasoning, which is based on being able to reuse content and avoid duplicating it in different areas.

---

You have one (rather large) IOTA-based task: **Send sensor data to the Tangle through Bluetooth**.
This would go into the **cIRI** section (soon to be 'Node software') because it's a task for the cIRI.

This large task can be split into two smaller IOTA-based tasks: **Create middleware to transform sensor data into transactions** and **Send the sensor data to the Tangle**.

We'd also have the following prerequisites to complete this task:
*  **Set up a cIRI node on an SBC** (which has its own prerequisites such as set up an SBC with a Bluetooth interface)
* **Set up a sensor node**

---

To map this structure out, we have:

IOTA-based tasks

-- **cIRI**
     -- Send sensor data to the Tange through Bluetooth (**prerequisite:** Run a cIRI node on an SBC)
          -- Write middleware to transform sensor data into transactions
          -- Send sensor data to the Tangle

In the future we could expand this guide to use Ict as well or any other IOTA tech. Therefore, this information doesn't belong in **General**.

General tasks that are prerequisites to IOTA-based ones

-- **General**
     -- Set up a sensor node
     -- Set up an SBC (with instructions for the Bluetooth interface as well as WiFi etc)

These general tasks can be reused in the future for other guides. They are generic so we should keep them in **General**.

**Pull request merged**
